### PR TITLE
feat: Add linting to styles

### PR DESCRIPTION
**Pull request by tofumatt**
I'd like for our styles to be linted (and preferably fixed in-place ala ES6 with Prettier). This is a WIP pull request to get that sorted, but it's pretty low-priority for now.

Afterward (or possibly alongside this): I'd like to explore PostCSS integration to get features like auto prefixing. It could be PostCSS will help us fix our styles as it has Style lint integrations, but I'm not sure. There are a lot of interlocking components when it comes to styles 😆

### CODE REVIEW

**Comment by tofumatt** [comment]
These aren't very strict rules by default, because Stylelint + autofixing + styled components work about 90% from what I can tell. Still: they warned us about some specificity linting mistakes and are handy to have. Mind a quick review, @sarahmonster?

**Comment by sarahmonster** [comment]
I've looked through the code changes and it seems good, but I'm guessing it would be helpful to pull down to test as well, which I'm doing now. 

Is there anything specific I should test here, or just make sure I can write CSS without it trying to get up in my grill?

**Comment by tofumatt** [comment]
> make sure I can write CSS without it trying to get up in my grill

That works. If it looks good even, we can tweak it as we go. If you start writing and it gets in your way, just let me know and we'll change things. I don't want the linting to be as annoying when it won't auto-fix ala Prettier.

**Comment by sarahmonster** [comment]
Tried it out and it seems fine—it doesn't alpha-order properties that I can see though.... is it supposed to?

**Comment by tofumatt** [comment]
It does not, because if you do it gets shirty about the order of the mixins. That's something I'll look to improve in the future.

**Comment by sarahmonster** [comment]
Cool! Let's use semicolons at the end of all CSS properties (I added some where there weren't any and pushed it) for consistency's sake and call it 👍

**Pull request merged**
